version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for the backend service
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    # Group patch and minor updates to reduce PR noise
    groups:
      python-backend-deps:
        update-types:
        - "minor"
        - "patch"

  # Maintain dependencies for the bot service
  - package-ecosystem: "pip"
    directory: "/bot"
    schedule:
      interval: "weekly"
    groups:
      python-bot-deps:
        update-types:
        - "minor"
        - "patch"

  # Maintain dependencies for the worker service
  - package-ecosystem: "pip"
    directory: "/worker"
    schedule:
      interval: "weekly"
    groups:
      python-worker-deps:
        update-types:
        - "minor"
        - "patch"