[tool.mypy]
# Tell Mypy where to find our source code
mypy_path = "backend:bot:worker"

# THIS IS THE FIX
explicit_package_bases = true

# Standard strict settings
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
show_error_codes = true

# Pydantic support
plugins = "pydantic.mypy"

[[tool.mypy.overrides]]
# Don't require type annotations for test files
module = "backend.tests.*"
disallow_untyped_defs = false

[tool.ruff]
# Same as pyproject.toml
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B"] # Standard flake8, isort, pyupgrade, flake8-bugbear
ignore = ["E501"]

[tool.black]
line-length = 88
target-version = ["py311"]
