
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend-fastapi'
    static_configs:
      - targets: ['backend:8000']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']