[tool.poetry]
name = "kurisu-core"
version = "1.0.0"
description = "Shared core library for the Kurisu project (e.g., logging)."
authors = ["salieri_dev <you@example.com>"]
packages = [{include = "kurisu_core", from = "src"}]
# Remove this line: readme = "README.md"

[tool.poetry.urls]
Homepage = "https://github.com/yourusername/kurisu"
Repository = "https://github.com/yourusername/kurisu"
Issues = "https://github.com/yourusername/kurisu/issues"

[tool.poetry.dependencies]
python = "^3.11"
structlog = "^25.4.0" # Use a specific version range

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"