server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

metrics_generator:
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
  processor:
    local_blocks: {}

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 24h

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]