apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: Jaeger
          matcherRegex: 'trace_id":"([^"]+)"'
          name: TraceID
          url: '/explore?orgId=1&left=["now-1h","now","Jaeger",{"query":"$${__value.raw}"}]'