name: CI Quality Checks

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  lint-and-format:
    name: Lint & Format (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ backend, bot, worker ] # kurisu_core is checked via others

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pipx install poetry

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: ./${{ matrix.service }}/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles(format('{0}/poetry.lock', matrix.service)) }}

      # Check for file changes to avoid unnecessary runs (optional but efficient)
      - name: Check for relevant file changes
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            ${{ matrix.service }}/**
            kurisu_core/**

      - name: Install Dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./${{ matrix.service }}
        # FIX: Removed --without dev to install ruff
        run: poetry install --no-interaction

      - name: Run Ruff Linter
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./${{ matrix.service }}
        run: poetry run ruff check .

      - name: Run Ruff Formatter (Check)
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./${{ matrix.service }}
        run: poetry run ruff format --check .

  type-check-and-test:
    name: Type Check & Test
    runs-on: ubuntu-latest
    needs: lint-and-format # This job runs only after linting succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pipx install poetry

      - name: Install ALL dependencies for MyPy
        run: |
          poetry -C backend install
          poetry -C bot install
          poetry -C worker install

      - name: Run MyPy Type Checker on the entire project
        # MyPy needs all dependencies installed to resolve imports correctly
        # We run it from the backend context as it has the mypy plugin for pydantic
        working-directory: ./backend
        run: poetry run mypy ../

      - name: Run Backend Tests
        working-directory: ./backend
        run: poetry run pytest